spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frame?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:com/ycd/common/repo/mybatis/xml/*.xml
mapper:
  identity: MYSQL
  not-empty: true
  style: camelhumpAndLowercase
  safe-delete: true
  safe-update: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
