spring:
  devtools:
    livereload:
      port: ${random.int[30000,40000]}
  profiles:
    include: datasource,custom,activiti
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  application:
    name: ycdApp
  autoconfigure:
    exclude: org.activiti.spring.boot.SecurityAutoConfiguration
logging:
  level:
    root: info
    org:
      springframework: info
    com:
      ycd: debug